### ISSUE TITLE
Help with embedded one to many MongoID search

### ISSUE THREAD

**Issue by lgs** [crowdint/rails3-jquery-autocomplete#131]
I'd need to look in a field (which is an array of strings) inside an  embedded doc ( see: http://mongoid.org/docs/relations/embedded/1-n.html ). Is that possible and if yes, how can I reppresent that in the controller ?

Something like the following ?
'autocomplete :brand, :name.embeddeddoc, :full => false'

**Comment by tirdadc** [comment]
Interested in this as well, but I assume this gem is abandoned at this point.

**Comment by bigtunacan** [comment]
@tirdadc The gem has not been abandoned.  We have added Rails 4 support, and the most recent gem release was just last month.  The official repo has moved however; which has been updated on the main page.

Issues should be opened on the new official repo.

Thanks.
