### ISSUE TITLE
SyntaxError: Unexpected token u with rails3-jquery-autocomplete 1.0.11 and jquery-rails 2.2.1

### ISSUE THREAD

**Issue by bollard** [crowdint/rails3-jquery-autocomplete#210]
After upgrading to rails3-jquery-autocomplete 1.0.11 (so i can upgrade to jQuery 1.9 in jquery-rails 2.2.1), i am getting the following error in the Chrome Developer console. Everything appears to work fine and the error is only logged once i click out of the input box.

```
Uncaught SyntaxError: Unexpected token u jquery.js:542
jQuery.extend.parseJSON jquery.js:542
e.autocomplete.change autocomplete-rails.js:17
$.Widget._trigger jquery.ui.widget.js:481
$.widget._change jquery.ui.autocomplete.js:477
(anonymous function) jquery.ui.widget.js:97
_on.blur jquery.ui.autocomplete.js:184
handlerProxy jquery.ui.widget.js:398
jQuery.event.dispatch jquery.js:3075
elemData.handle jquery.js:2751
```

StackOverflow suggests that "undefined" is being passed into parseJSON...?

**Comment by suebphatt** [comment]
@adahl +1 thank you!
