### ISSUE TITLE
DEPRECATION WARNING

### ISSUE THREAD

**Issue by KindleL** [crowdint/rails3-jquery-autocomplete#284]
```
DEPRECATION WARNING: input method now accepts a `wrapper_options` argument. The method definition without the argument is deprecated and will be removed in the next Simple Form version. Change your code from:

    def input

to

    def input(wrapper_options)

See https://github.com/plataformatec/simple_form/pull/997 for more information.
```

**Comment by bigtunacan** [comment]
This sounds like something that needs to be addressed for SimpleForm.  Personally, I have not used SimpleForm before, but instead I use Formtastic.  A pull request for this would be gladly accepted though.  The code relating to this issues is in `lib/rails3-jquery-autocomplete/simple_form_plugin.rb`
