### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by glafir** [crowdint/rails3-jquery-autocomplete#288]
I want to use [Sourcegraph](https://sourcegraph.com) for rails3-jquery-autocomplete code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/crowdint/rails3-jquery-autocomplete. (It should only take 30 seconds.)

Thank you!

**Comment by bigtunacan** [comment]
@glafir New issues should be opened on https://github.com/bigtunacan/rails-jquery-autocomplete.  That is the officially maintained fork.  This branch is deprecated. Thanks.
