### ISSUE TITLE
1.0.11 was last release?

### ISSUE THREAD

**Issue by stevenvachon** [crowdint/rails3-jquery-autocomplete#289]
Is 1.0.14 going to be released? Using a git endpoint can be risky if the repo has unresolved issues.

**Comment by bigtunacan** [comment]
@stevenvachon 

I'm a little confused by your question.  The last (and final) released version on this fork was 1.0.15 back in January of this year https://rubygems.org/gems/rails3-jquery-autocomplete/versions

As shown on the README.md I have officially forked over to https://github.com/bigtunacan/rails-jquery-autocomplete and changed the gem name to "rails-jquery-autocomplete"  There have been 3 releases this year.  This was some confusion where people were assuming only Rails 3 was supported and as I move towards Rails 4 and beyond I felt now was as good a time as any to clear that up.

**Comment by m0dd3r** [comment]
I was confused by thistoo @bigtunacan and @stevenvachon.  The last tagged release in github is 1.0.11, but now that I look over at rubygems, I see 1.0.15, so it looks like it's just the tag that's missing.
