### ISSUE TITLE
delay and minLength options don't seem to work

### ISSUE THREAD

**Issue by noahschwartz** [crowdint/rails3-jquery-autocomplete#67]
<%= autocomplete_field_tag :entity, "<Start typing here>", "/cats/autocomplete", :delay => 10000 %>

I would expect my results to take a long time to come up but, it seems to be taking the default value for delay. Similarly, minLength doesn't seem to work. Am I just doing something wrong?

**Comment by yanyingwang** [comment]
@bigtunacan We should document the usage of it to README file, I think.

**Comment by yanyingwang** [comment]
@bigtunacan  never mind, I've figured it out. But after putting code `'min-length' => 0`, shouldn't this input field give a dropdown list when cursor putted in there?

For anyone who also do google search coming here,now the right code for 'minLength' should be like this:

`f.autocomplete_field :title_name, autocomplete_title_name_losts_path, 'data-auto-focus' => true, 'min-length' => 0, autofocus: true`

and this for simple_form user:

`f.input :title_name, url: autocomplete_title_name_losts_path, as: :autocomplete, autofocus: true, input_html: { value: '1', 'data-auto-focus' => true, 'min-length' => 0 }`.

**Comment by knightq** [comment]
@bigtunacan 
> minLength is supported these days on master.

What about delay?
