### ISSUE TITLE
Everybody complains about this error... You need solve it.

### ISSUE THREAD

**Issue by eduardo82** [crowdint/rails3-jquery-autocomplete#72]
See my example.

My controller 

class MessagesController < ApplicationController
  autocomplete :user, :name
.......

My Model

class Message < ActiveRecord::Base
  belongs_to :user
end

My routes.rb

  resources :messages do
    get :autocomplete_user_name, :on => :collection
  end

My form
    <%= f.autocomplete_field :user_name, autocomplete_user_name_messages_path %>

My table messages

```
create_table :messages do |t|
  t.integer :user_id
  t.string :subject
  t.string :contents
  t.timestamps
end
```

My view application
  <%= javascript_include_tag :defaults, "rails.js", 'jquery-1.5', 'jquery-ui-1.8.14.custom.min', "autocomplete-rails.js" %>

And I got the same error lke everybody.

undefined method `user_name' for #Message:0x103a135c0
Extracted source (around line #16):

13: 
14:   <div class="field">
15:     <%= f.label :user_id, "Para" %><br />
16:     <%= f.autocomplete_field :user_name, autocomplete_user_name_messages_path %>
17:   </div>
18:   <div class="field">
19:     <%= f.label :subject, "Assunto" %><br />

**Comment by yanyingwang** [comment]
I was wondering, shouldn't this be done by a macro method implemented in `jquery-autocomplete`gem  by default? Since there is so many people doing it this way with associations.
